### ISSUE TITLE
[Question] v2.10.4 after I configure the SSL certificate, I can't open the web page using port 5001

### ISSUE THREAD

**Issue by stefen-jms** [jumpserver/jumpserver#6255]
**请描述您的问题.**
![企业微信截图_16232926614958](https://user-images.githubusercontent.com/80803090/121456344-810a8000-c9d8-11eb-934d-2aae618117fb.png)
![企业微信截图_16232927623453](https://user-images.githubusercontent.com/80803090/121456353-836cda00-c9d8-11eb-81ce-b4390bb2d13a.png)

**Comment by stefen-jms** [comment]
![企业微信截图_16232930061830](https://user-images.githubusercontent.com/80803090/121456442-aeefc480-c9d8-11eb-9b49-e99646a20534.png)

**Comment by stefen-jms** [comment]
when the version was v2.9.2, there is no such problem

**Comment by wojiushixiaobai** [comment]
When USE_LB=1,
Invalid parameter HTTP_PORT, HTTPS_PORT, SSH_PORT
Please use LB_HTTPS_PORT=5001

If you don't want to use HTTPS
Please do not set USE_LB=1

example
```
HTTP_PORT=8080
HTTPS_PORT=5001
SSH_PORT=2222

USE_LB=0                     # When USE_LB=0
LB_HTTP_PORT=80      # Invalid setting
LB_HTTPS_PORT=443  # Invalid setting
LB_SSH_PORT=2222    # Invalid setting
```
or
```
HTTP_PORT=8080             # Invalid setting
HTTPS_PORT=8443           # Invalid setting
SSH_PORT=2222               # Invalid setting

USE_LB=1                         # When USE_LB=1
LB_HTTP_PORT=8080
LB_HTTPS_PORT=5001
LB_SSH_PORT=2222
```

**Comment by stefen-jms** [comment]
> 当USE_LB=1时，
> 参数HTTP_PORT、HTTPS_PORT、SSH_PORT无效
> 请使用LB_HTTPS_PORT=5001
> 
> 如果您不想使用 HTTPS
> 请不要设置 USE_LB=1
> 
> 例子
> 
> ```
> HTTP_PORT=8080
> HTTPS_PORT=5001
> SSH_PORT=2222
> 
> USE_LB=0                     # When USE_LB=0
> LB_HTTP_PORT=80      # Invalid setting
> LB_HTTPS_PORT=443  # Invalid setting
> LB_SSH_PORT=2222    # Invalid setting
> ```
> 
> 或者
> 
> ```
> HTTP_PORT=8080             # Invalid setting
> HTTPS_PORT=8443           # Invalid setting
> SSH_PORT=2222               # Invalid setting
> 
> USE_LB=1                         # When USE_LB=1
> LB_HTTP_PORT=8080
> LB_HTTPS_PORT=5001
> LB_SSH_PORT=2222
> ```

i see, i will try that, but in version2.9.3, i just set like this and it works, but v2.10.4 can't works

**Comment by wojiushixiaobai** [comment]
Please execute
```bash
cd /opt/jumpserver-installer-v2.10.4
jmscl.sh status
```
Check for unhealthy containers..
If all containers are healthy, you may have to check the firewall and iptables settings..

**Comment by stefen-jms** [comment]
> 请执行
> 
> ```shell
> cd /opt/jumpserver-installer-v2.10.4
> jmscl.sh 状态
> ```
> 
> 检查不健康的容器。
> 如果所有容器都健康，您可能需要检查防火墙和 iptables 设置。

i check that. they are all healthy, i just set as you said, will it affect the certificate, i need to access by the domain later

**Comment by wojiushixiaobai** [comment]
If you are configuring HTTPS domain access directly on the jumpserver server, you can do this

- [ ] Copy nginx certificate file to `/opt/jumpserver/config/nginx/cert` directory
- [ ] Modify configuration file `/opt/jumpserver/config/config.txt`
```vim
HTTP_PORT=8080             # Invalid setting
HTTPS_PORT=8443           # Invalid setting
SSH_PORT=2222               # Invalid setting

USE_LB=1                         # When USE_LB=1
LB_HTTP_PORT=8080
LB_HTTPS_PORT=5001
LB_SSH_PORT=2222
```

- [ ] Modify configuration file `/opt/jumpserver/config/nginx/lb_http_server.conf`
```vim
# Todo: May be can auto discovery
upstream http_server {
  sticky name=jms_route;
  server nginx:80;
  # server HOST2:8080; 
}

server {
  listen 80;
  server_name demo.jumpserver.org;  # Change to your own domain
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl;
  server_name demo.jumpserver.org;      # Change to your own domain
  server_tokens off;
  ssl_certificate cert/server.crt;      # Change to your own certificate
  ssl_certificate_key cert/server.key;  # Change to your own certificate
  ssl_session_timeout 1d;
  ssl_session_cache shared:MozSSL:10m;
  ssl_session_tickets off;
  ssl_protocols TLSv1.1 TLSv1.2;

  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers off;
  add_header Strict-Transport-Security "max-age=63072000" always;

  client_max_body_size 5000m; 

  location / {
    proxy_pass http://http_server;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;

    proxy_ignore_client_abort on;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 6000;
  }
}
```

**Comment by stefen-jms** [comment]
i see. thanks a lot @wojiushixiaobai

**Comment by stefen-jms** [comment]
@wojiushixiaobai got a new problem,  i can't connect to any assets.
![image](https://user-images.githubusercontent.com/80803090/121618648-b925c780-ca99-11eb-869b-7a2184260b62.png)

**Comment by wojiushixiaobai** [comment]
How do you set up reverse proxy?
Can you provide relevant settings, similar to my reply above..

**Comment by stefen-jms** [comment]
Sure
![image](https://user-images.githubusercontent.com/80803090/121618847-22a5d600-ca9a-11eb-89f4-0c2a55ed5924.png)
![image](https://user-images.githubusercontent.com/80803090/121618929-40733b00-ca9a-11eb-9d13-72c1dbdd115e.png)

**Comment by stefen-jms** [comment]
I did not modify anything after successfully logging in and connecting the assets yesterday. But I found that I can't connect the assets today

**Comment by stefen-jms** [comment]
The version of the plug-in
![image](https://user-images.githubusercontent.com/80803090/121619628-7c5ad000-ca9b-11eb-8047-a1867ee4cc03.png)

**Comment by wojiushixiaobai** [comment]
If your upper layer has additional nginx reverse proxy, don't forget to add websocket related parameters..
```
server {

    listen 5001;
    server_name demo.jumpserver.org;   # Change to your own domain

    client_max_body_size 4096m; 

    location / {
            # The IP here is the IP of the back-end jumpserver, use HTTP_PORT
            proxy_pass http://<your_server>:8080;    # Change to your server
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";

**Comment by stefen-jms** [comment]
> If your upper layer has additional nginx reverse proxy, don't forget to add websocket related parameters..
> 
> ```
> server {
> 
>     listen 5001;
>     server_name demo.jumpserver.org;   # Change to your own domain
> 
>     client_max_body_size 4096m; 
> 
>     location / {
>             # The IP here is the IP of the back-end jumpserver, use HTTP_PORT
>             proxy_pass http://<your_server>:8080;    # Change to your server
>             proxy_http_version 1.1;
>             proxy_buffering off;
>             proxy_request_buffering off;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "upgrade";
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header Host $host;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }
> }
> ```
> 
> proxy_http_version 1.1;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";

@wojiushixiaobai there is no additional nginx reverse proxy in upper layer, i just want to configure https domain access

**Comment by wojiushixiaobai** [comment]
I don't have any more suggestions..
Do you need remote technical support?

teamviewer?

**Comment by stefen-jms** [comment]
> I don't have any more suggestions..
> Do you need remote technical support?
> 
> teamviewer?

Does the server have any logs to view

**Comment by stefen-jms** [comment]
![image](https://user-images.githubusercontent.com/80803090/121625860-e462e380-caa6-11eb-924e-4ff80105621a.png)
@wojiushixiaobai Is it a port or network problem

**Comment by wojiushixiaobai** [comment]
If your upper layer has additional nginx reverse proxy, don't forget to add websocket related parameters..
```
server {

    listen 5001;
    server_name demo.jumpserver.org;   # Change to your own domain

    client_max_body_size 4096m; 

    location / {
            # The IP here is the IP of the back-end jumpserver, use HTTP_PORT
            proxy_pass http://<your_server>:8080;    # Change to your server
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_request_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";

**Comment by stefen-jms** [comment]
> If your upper layer has additional nginx reverse proxy, don't forget to add websocket related parameters..
> 
> ```
> server {
> 
>     listen 5001;
>     server_name demo.jumpserver.org;   # Change to your own domain
> 
>     client_max_body_size 4096m; 
> 
>     location / {
>             # The IP here is the IP of the back-end jumpserver, use HTTP_PORT
>             proxy_pass http://<your_server>:8080;    # Change to your server
>             proxy_http_version 1.1;
>             proxy_buffering off;
>             proxy_request_buffering off;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "upgrade";
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header Host $host;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }
> }
> ```
> 
> proxy_http_version 1.1;
> proxy_set_header Upgrade $http_upgrade;
> proxy_set_header Connection "upgrade";
> 
> [WebSocket proxying](http://nginx.org/en/docs/http/websocket.html)
> [JumpServer proxying](https://docs.jumpserver.org/zh/master/admin-guide/proxy/)

there is no upper nginx reverse proxy

**Comment by wojiushixiaobai** [comment]
Hey, man. 
I mean you have to check your websocket settings. 
Your error report indicates that websocket cannot be connected.

**Comment by stefen-jms** [comment]
> Hey, man.
> I mean you have to check your websocket settings.
> Your error report indicates that websocket cannot be connected.

@wojiushixiaobai the setting of the websocket is correct (T.T). I found a strange thing,i can access to the assets in some subnet of my company, but the subnet of my PC can't access,  indicated that websocket cannot be connected.

**Comment by stefen-jms** [comment]
![image](https://user-images.githubusercontent.com/80803090/121671060-b26e7300-cae0-11eb-9c9e-b3cc720c02dd.png)
![image](https://user-images.githubusercontent.com/80803090/121671082-b9958100-cae0-11eb-896b-12a3c0e487f8.png)

**Comment by wojiushixiaobai** [comment]
I may need to remote your computer desktop to see the phenomenon in order to know the problem. Is it convenient for me to do so?

For example, remote connection using [TeamViewer](https://www.teamviewer.com/) tools.

**Comment by stefen-jms** [comment]
> I may need to remote your computer desktop to see the phenomenon in order to know the problem. Is it convenient for me to do so?
> 
> For example, remote connection using [TeamViewer](https://www.teamviewer.com/) tools.

maybe tomorrow?

**Comment by wojiushixiaobai** [comment]
sure，About what time?

**Comment by stefen-jms** [comment]
> sure，About what time?

2PM?

**Comment by wojiushixiaobai** [comment]
I'm in China. Maybe we have jet lag. Is 14:00 UTC + 8?

**Comment by stefen-jms** [comment]
> I'm in China. Maybe we have jet lag. Is 14:00 UTC + 8?
I am in CHina too. no jet lag.

**Comment by wojiushixiaobai** [comment]
ok，Maybe we can communicate with WeChat?

https://docs.jumpserver.org/zh/master/about/contact/

**Comment by stefen-jms** [comment]
> ok，Maybe we can communicate with WeChat?
> 
> https://docs.jumpserver.org/zh/master/about/contact/

sure
